Repository Salzian/bevy_fmod, pull requests merged in 2023-10, with the labels that each got.

#45 Fix audio source toggle behavior
  src/components/audio_source.rs
Labels: bug

#43 Split spatial example
  Cargo.toml
  examples/audio_control.rs
  examples/spatial.rs
Labels: documentation

#52 Add build script for Linux, update readme.
  .gitignore
  README.md
  build.rs
Labels: documentation, enhancement

#55 Better specification of versions in Cargo.toml
  Cargo.toml
Labels: dependencies

#53 Make Velocity optional
  src/components/audio_listener.rs
  src/components/audio_source.rs
  src/components/bundles.rs
  src/components/velocity.rs
Labels: bug, enhancement, :no_entry_sign: blocked
