Repository Salzian/bevy_fmod, pull requests merged in 2023-09, with the labels that each got.

#10 Make repo layout slimmer and refactor example project
  .gitignore
  .idea/bevy_fmod.iml
  Cargo.lock
  Cargo.toml
  README.md
  crate/Cargo.toml
  examples/hello_world.rs
  examples/hello_world/Cargo.lock
  examples/hello_world/Cargo.toml
  src/lib.rs
  src/play_sound_event.rs
  src/plugin.rs
Labels: enhancement

#11 Bump version to v0.2.0
  .idea/rust.xml
  Cargo.toml
  README.md
Labels: bug, documentation, dependencies

#23 Update libfmod to thread-safe variant
  Cargo.toml
Labels: dependencies

#25 Init FMOD with right-handed coordinate system
  src/fmod_studio.rs
Labels: bug, enhancement

#26 Add support for spatial audio
  Cargo.toml
  examples/minimal.rs
  examples/spatial.rs
  src/attributes_3d.rs
  src/components/audio_listener.rs
  src/components/audio_source.rs
  src/components/mod.rs
  src/components/velocity.rs
  src/fmod_plugin.rs
  src/fmod_studio.rs
  src/lib.rs
  src/play_sound_event.rs
  src/plugin.rs
Labels: enhancement

#31 Setup dependabot for automatic version updates
  .github/dependabot.yml
Labels: repo

#33 Use FMOD Studio Examples
  .gitignore
  README.md
  examples/minimal.rs
  examples/spatial.rs
Labels: enhancement

#34 Fix dependabot config: labels array
  .github/dependabot.yml
Labels: bug, repo

#35 Reduce clutter in spatial example
  examples/spatial.rs
Labels: documentation

#39 Fix velocity & doppler effect
  src/components/velocity.rs
Labels: bug

#38 Live update
  Cargo.toml
  README.md
  src/fmod_studio.rs
Labels: enhancement

#41 Introduce STYLEGUIDE.md
  STYLEGUIDE.md
Labels: documentation, repo

#32 Add support for FMOD local parameters
  Cargo.toml
  examples/minimal.rs
  examples/parameters.rs
  examples/spatial.rs
  src/components/audio_source.rs
Labels: enhancement

#40 Introduce prelude module
  examples/minimal.rs
  examples/parameters.rs
  examples/spatial.rs
  src/components/audio_source.rs
  src/fmod_studio.rs
  src/lib.rs
  src/prelude.rs
Labels: enhancement

#37 Improve examples docs & setup
  README.md
  examples/minimal.rs
  examples/parameters.rs
  examples/spatial.rs
Labels: documentation, enhancement

#42 Bump version to v0.3
  Cargo.toml
Labels: enhancement
